### PR TITLE
Crash fix for mp_important color

### LINKED ISSUE #450: `mp_importantColor` crashes on some images.
@malectro I was looking at using your algorithm on some images it crashes in the loop because the data array is accessed beyond the bounds. I can't really figure out why as the various CGBitmapContextGet* functions return the same values.

```
   // only attempt to quantize the header
    NSUInteger l = (NSUInteger) ceil(self.size.width * 124.0f);
    for (NSUInteger i = 40 * 640; i < l; i++) {
        uint8_t red = data[i * 4 + 2];
        uint8_t green = data[i * 4 + 1]; // **** CRASHES HERE WHEN i = 40*640 ***
        uint8_t blue = data[i * 4 + 0];
        NSInteger hexColor = (red >> 2) + ((green >> 2) << 6) + ((blue >> 2) << 12);

        if (hexColor > 0 && hexColor < 2621443 && red + green + blue < 255 + 255 + 200 && red != blue && blue != green && green != red) {
            colorIndices[hexColor]++;
        }
    }
```

### PR DESCRIPTION
**Pull request by samgreen**
Fix mp_important color to be more safe, and leverage CoreGraphics instead of hard coded magic numbers.
Resolves #450

### CODE REVIEW

File: Mixpanel/UIImage+MPAverageColor.m [hunk 1]
```diff
@@ -8,59 +8,73 @@ @implementation UIImage (MPAverageColor)
...
-    for (NSUInteger i = 40 * 640; i < l; i++) {
-        uint8_t red = data[i * 4 + 2];
-        uint8_t green = data[i * 4 + 1];
-        uint8_t blue = data[i * 4 + 0];
-        NSInteger hexColor = (red >> 2) + ((green >> 2) << 6) + ((blue >> 2) << 12);
-
-        if (hexColor > 0 && hexColor < 2621443 && red + green + blue < 255 + 255 + 200 && red != blue && blue != green && green != red) {
-            colorIndices[hexColor]++;
+- (UIColor *)mp_importantColor {
+    static const size_t kImageStartRow = 40;
```
Comment (yarneo) [inline Mixpanel/UIImage+MPAverageColor.m]: why are we starting at row 40?

File: Mixpanel/UIImage+MPAverageColor.m [hunk 2]
```diff
@@ -8,59 +8,73 @@ @implementation UIImage (MPAverageColor)
...
+    static const size_t kNumberOfRows = 124;
```
Comment (yarneo) [inline Mixpanel/UIImage+MPAverageColor.m]: Does this bind the image to be only one size?

File: Mixpanel/UIImage+MPAverageColor.m (hunk 1 above)
Comment (samgreen) [inline Mixpanel/UIImage+MPAverageColor.m]: This is legacy code. We're just updating it without changing the behavior.

File: Mixpanel/UIImage+MPAverageColor.m (hunk 2 above)
Comment (samgreen) [inline Mixpanel/UIImage+MPAverageColor.m]: Fixed.

**Comment by yarneo** [comment]
Looks good!
